name: "detect_stalled"

on:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  pull-requests: write

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/detect_stalled.yml@main
    with:
      pr-stale-days: 180 # mark stale after 6 months
      pr-close-days: -1  # never close automatically
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}
