name: "detect_stalled"

on:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  issues: write
  pull-requests: write

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/pr_check_stalled.yml@main
    with:
      stale-days: 180
      close-days: -1
