name: "pr_opened"

on:
  repository_dispatch:
    types:
      - pull_request_opened
      - pull_request_reopened

permissions:
  pull-requests: write
  checks: read

concurrency:
  group: pullreq-${{ github.event.client_payload.number }}

jobs:
  lint-contribution:
    uses: roc-streaming/ci/.github/workflows/pr_lint_contrib.yml@main
    with:
      pr-number: ${{ github.event.client_payload.number }}
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}

  lint-first-time:
    uses: roc-streaming/ci/.github/workflows/pr_lint_first_time.yml@main
    with:
      pr-number: ${{ github.event.client_payload.number }}
      development-branch: "develop"
      guidelines-link: >-
        https://roc-streaming.org/toolkit/docs/development/contribution_guidelines.html
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}

  lint-target-branch:
    uses: roc-streaming/ci/.github/workflows/pr_lint_target_branch.yml@main
    with:
      pr-number: ${{ github.event.client_payload.number }}
      development-branch: "develop"
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}

  lint-linked-issue:
    uses: roc-streaming/ci/.github/workflows/pr_lint_linked_issue.yml@main
    with:
      pr-number: ${{ github.event.client_payload.number }}
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}

  set-status:
    uses: roc-streaming/ci/.github/workflows/pr_status_opened.yml@main
    with:
      pr-number: ${{ github.event.client_payload.number }}
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}
