name: "triggers"

on:
  push:
    branches:
      - master

permissions:
  actions: write

concurrency:
  group: triggers

jobs:
  main:
    strategy:
      matrix:
        include:
          - repo: roc-go
            branch: main

          - repo: roc-java
            branch: main

          - repo: roc-pulse
            branch: main

          - repo: roc-vad
            branch: main

          - repo: rocd
            branch: main

          - repo: roc-streaming.github.io
            branch: source

    name: ${{ matrix.repo }}
    uses: roc-streaming/ci/.github/workflows/trigger_build.yml@main
    with:
      repo: ${{ matrix.repo }}
      branch: ${{ matrix.branch }}
    secrets:
      ci-token: ${{ secrets.REPO_ACTIONS }}
